<?php

namespace Yomat\CatalogBundle\Repository;

/**
 * ConsumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumerRepository extends \Doctrine\ORM\EntityRepository
{
}
