<?php

namespace Yomat\CatalogBundle\Repository;

/**
 * MediaItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaItemRepository extends \Doctrine\ORM\EntityRepository
{
}
