<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEvents($date){
        $qb = $this -> createQueryBuilder('event')
      /*      -> where('event.date > :date')
            -> setParameter('date', $date)
            -> orderBy('event.date', 'DESC')*/
        ;
        $query = $qb -> getQuery();
// 		return $query -> getResult();
        //return new \Doctrine\ORM\Tools\Pagination\Paginator($query);
        return $query -> getResult();
    }

}
