<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEvents($date, $eventType){
        if ($eventType === NULL || $eventType == "all_events")
            $qb = $this -> _em -> createQueryBuilder()
                        -> select('e')
                        -> from('AppBundle:Event', 'e');
        else
            $qb = $this -> _em -> createQueryBuilder()
                -> select('e')
                -> from('AppBundle:Event', 'e')
                -> where('e.type = :eventType')
                -> setParameter('eventType', $eventType);
 		return $qb -> getQuery() -> getResult();
    }

    public function getEvent($id){
        return null;
    }
}
