<?php

namespace AppBundle\Repository;

/**
 * EventGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventGenreRepository extends \Doctrine\ORM\EntityRepository
{
}
