<?php

namespace AppBundle\Repository;

/**
 * EventCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
