<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEvents($date){
        $qb = $this -> _em -> createQueryBuilder()
                    -> select('e')
                    -> from('AppBundle:Event', 'e');
      /*      -> where('event.date > :date')
            -> setParameter('date', $date)
            -> orderBy('event.date', 'DESC')
      ;*/
        /*$query = $qb -> getQuery()*/;
 		return $qb -> getQuery() -> getResult();
        /*$results = $query -> getArrayResult();
        return $results;*/
    }

}
