<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{


    public function getPlaces(){
        $qb = $this -> _em -> createQueryBuilder()
            -> select('p')
            -> from('AppBundle:Place', 'p');
        return $qb -> getQuery() -> getResult();
    }

    public function getPlacesJSON(){
        $qb = $this -> _em -> createQueryBuilder()
            -> select('p')
            -> from('AppBundle:Place', 'p');
        return $qb -> getQuery() -> getArrayResult();
    }

    public function getPlacesLike($search_term){
        $qb = $this -> _em -> createQueryBuilder()
            -> select('p')
            -> from('AppBundle:Place', 'p')
            -> where('p.name LIKE :search_term')
            -> setParameter('search_term', '%'.$search_term.'%')
            -> orderBy('p.name', 'ASC')
        ;
        return $qb -> getQuery() -> getResult();
    }

    public function getPlacesLikeJSON($search_term){
        $qb = $this -> _em -> createQueryBuilder()
            -> select('p')
            -> from('AppBundle:Place', 'p')
            -> where('p.name LIKE :search_term')
            -> setParameter('search_term', '%'.$search_term.'%')
            -> orderBy('p.name', 'ASC')
            ;
        return $qb -> getQuery() -> getArrayResult();
    }
}
