app_groupe:
    resource: "@AppBundle/Controller/GroupeController.php"
    type:     annotation

yomat_catalog:
    resource: "@YomatCatalogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# utiliser les routes symfony dans du javascript
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"